# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # #                                   НЕ РЕДАКТИРОВАТЬ!!                                  # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

external_components:
  - source:
      url: https://github.com/malekabd2019-cell/uneva-ac--esphome.git
      type: git
      ref: main
    components: [ tclac ]
    refresh: 0s

esphome:
  name: ${device_name}
  min_version: 2023.3.0
  friendly_name: ${humanly_name}

uart:
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  stop_bits: 1
  rx_pin: ${uart_rx}
  tx_pin: ${uart_tx}

api:
  encryption:
    key: "${api_key}"

ota:
- platform: esphome
  password: "${ota_pass}"

wifi:
  id: "${device_name}_wifi"
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: "${recovery_pass}"

captive_portal:

logger:
  baud_rate: 0

select:
  - platform: template
    name: "وضع المولد (تقييد القدرة)"
    id: generator_mode_select
    icon: "mdi:generator-portable"
    options:
      - "Off"
      - "Level 1"
      - "Level 2"
      - "Level 3"
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: !lambda |-
          uint8_t mode = id(generator_mode_select).active_index().value_or(0);
          id(${device_name}climate).set_gen_mode(mode);

climate:
  - platform: tclac
    name: "${device_name} Climate"
    id: ${device_name}climate
    supports_cool: true
    supports_heat: true
    supports_fan_only: true
    supports_dry: true
    
