# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # #                                   НЕ РЕДАКТИРОВАТЬ!!                                  # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Компонент климата (تم التوجيه للمستودع والفرع الصحيح)
external_components:
  - source:
      url: https://github.com/malekabd2019-cell/uneva-ac--esphome.git
      type: git
      ref: main
    components: [ tclac ]
    refresh: 0s

# Конфигурация ESPHome
esphome:
  name: ${device_name}
  min_version: 2023.3.0
  friendly_name: ${humanly_name}
  on_boot:
    priority: -100
    then:
      lambda: !lambda |-
        id(${device_name}climate).set_beeper_state(false);
        id(${device_name}climate).set_force_mode_state(false);
        
        // استعادة وضع المولد المحفوظ عند إقلاع الجهاز
        id(${device_name}climate).set_gen_mode(id(generator_mode_select).active_index());

        if (id(display_mode).state){
          id(${device_name}climate).set_display_state(true);
        } else {
          id(${device_name}climate).set_display_state(false);
        }
        if (id(ledflash_mode).state){
          id(${device_name}climate).set_module_display_state(true);
        } else {
          id(${device_name}climate).set_module_display_state(false);
        }
        
        if (id(vswing).active_index() == 0){
          id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::UP_DOWN);
        } else if (id(vswing).active_index() == 1){
          id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::UPSIDE);
        } else if (id(vswing).active_index() == 2){
          id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::DOWNSIDE);
        }

        if (id(hswing).active_index() == 0){
          id(${device_name}climate).set_horizontal_swing_direction(esphome::tclac::HorizontalSwingDirection::LEFT_RIGHT);
        } else if (id(hswing).active_index() == 1){
          id(${device_name}climate).set_horizontal_swing_direction(esphome::tclac::HorizontalSwingDirection::LEFTSIDE);
        } else if (id(hswing).active_index() == 2){
          id(${device_name}climate).set_horizontal_swing_direction(esphome::tclac::HorizontalSwingDirection::CENTER);
        } else if (id(hswing).active_index() == 3){
          id(${device_name}climate).set_horizontal_swing_direction(esphome::tclac::HorizontalSwingDirection::RIGHTSIDE);
        }
        
        if (id(vfixing).active_index() == 0){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::LAST);
        } else if (id(vfixing).active_index() == 1){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::MAX_UP);
        } else if (id(vfixing).active_index() == 2){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::UP);
        } else if (id(vfixing).active_index() == 3){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::CENTER);
        } else if (id(vfixing).active_index() == 4){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::DOWN);
        } else if (id(vfixing).active_index() == 5){
          id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::MAX_DOWN);
        }
        
        if (id(hfixing).active_index() == 0){
          id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::LAST);
        } else if (id(hfixing).active_index() == 1){
          id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::MAX_LEFT);
        } else if (id(hfixing).active_index() == 2){
          id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::LEFT);
        } else if (id(hfixing).active_index() == 3){
          id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::CENTER);
        } else if (id(hfixing).active_index() == 4){
          id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::RIGHT);
        } else if (id(hfixing).active_index() == 5){
          id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::MAX_RIGHT);
        }
        if (id(beep_mode).state){
          id(${device_name}climate).set_beeper_state(true);
        } else {
          id(${device_name}climate).set_beeper_state(false);
        }
        if (id(force_mode).state){
          id(${device_name}climate).set_force_mode_state(true);
        } else {
          id(${device_name}climate).set_force_mode_state(false);
        }

uart:
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  stop_bits: 1
  rx_pin: ${uart_rx}
  tx_pin: ${uart_tx}

api:
  encryption:
    key: "${api_key}"

ota:
- platform: esphome
  password: "${ota_pass}"

wifi:
  id: "${device_name}_wifi"
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: "${recovery_pass}"

captive_portal:

logger:
  baud_rate: 0

switch:
  - name: Beeper
    platform: template
    device_class: switch
    id: beep_mode
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_beeper_state(true);
    on_turn_off:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_beeper_state(false);
  
  - name: Display
    platform: template
    device_class: switch
    id: display_mode
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_display_state(true);
    on_turn_off:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_display_state(false);
  
  - name: Display on module
    platform: template
    device_class: switch
    id: ledflash_mode
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_module_display_state(true);
    on_turn_off:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_module_display_state(false);
          
  - name: Force config
    platform: template
    device_class: switch
    id: force_mode
    entity_category: config
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_force_mode_state(true);
    on_turn_off:
      then:
        lambda: !lambda |-
          id(${device_name}climate).set_force_mode_state(false);

select:
  # ==========================================
  # قائمة زر وضع المولد الأصلي المدمج بالكامل
  # ==========================================
  - platform: template
    name: "Generator Mode"
    id: generator_mode_select
    entity_category: config
    options:
      - "Off"
      - "Level 1"
      - "Level 2"
      - "Level 3"
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: !lambda |-
          uint8_t mode = id(generator_mode_select).active_index();
          id(${device_name}climate).set_gen_mode(mode);

  - platform: template
    name: Vertical swing
    id: vswing
    entity_category: config
    options:
      - "Сверху вниз"
      - "В верхней половине"
      - "В нижней половине"
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: !lambda |-
          if (id(vswing).active_index() == 0){
            id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::UP_DOWN);
          } else if (id(vswing).active_index() == 1){
            id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::UPSIDE);
          } else if (id(vswing).active_index() == 2){
            id(${device_name}climate).set_vertical_swing_direction(esphome::tclac::VerticalSwingDirection::DOWNSIDE);
          }

  - platform: template
    name: Horizontal swing
    id: hswing
    entity_category: config
    options:
      - "Слева направо"
      - "В левой части"
      - "В центре"
      - "В правой части"
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: !lambda |-
          if (id(hswing).active_index() == 0){
            id(${device_name}climate).set_horizontal_swing_direction(esphome::tclac::HorizontalSwingDirection::LEFT_RIGHT);
          } else if (id(hswing).active_index() == 1){
            id(${device_name}climate).set_horizontal_swing_direction(esphome::tclac::HorizontalSwingDirection::LEFTSIDE);
          } else if (id(hswing).active_index() == 2){
            id(${device_name}climate).set_horizontal_swing_direction(esphome::tclac::HorizontalSwingDirection::CENTER);
          } else if (id(hswing).active_index() == 3){
            id(${device_name}climate).set_horizontal_swing_direction(esphome::tclac::HorizontalSwingDirection::RIGHTSIDE);
          }

  - platform: template
    name: Vertical fixing
    id: vfixing
    entity_category: config
    options:
      - "Последнее положение"
      - "До упора вверх"
      - "В верхней половине"
      - "По середине"
      - "В нижней половине"
      - "До упора вниз"
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: !lambda |-
          if (id(vfixing).active_index() == 0){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::LAST);
          } else if (id(vfixing).active_index() == 1){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::MAX_UP);
          } else if (id(vfixing).active_index() == 2){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::UP);
          } else if (id(vfixing).active_index() == 3){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::CENTER);
          } else if (id(vfixing).active_index() == 4){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::DOWN);
          } else if (id(vfixing).active_index() == 5){
            id(${device_name}climate).set_vertical_airflow(esphome::tclac::AirflowVerticalDirection::MAX_DOWN);
          }

  - platform: template
    name: Horizontal fixing
    id: hfixing
    entity_category: config
    options:
      - "Последнее положение"
      - "До упора влево"
      - "В левой половине"
      - "По середине"
      - "В правой половине"
      - "До упора вправо"
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: !lambda |-
          if (id(hfixing).active_index() == 0){
            id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::LAST);
          } else if (id(hfixing).active_index() == 1){
            id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::MAX_LEFT);
          } else if (id(hfixing).active_index() == 2){
            id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::LEFT);
          } else if (id(hfixing).active_index() == 3){
            id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::CENTER);
          } else if (id(hfixing).active_index() == 4){
            id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::RIGHT);
          } else if (id(hfixing).active_index() == 5){
            id(${device_name}climate).set_horizontal_airflow(esphome::tclac::AirflowHorizontalDirection::MAX_RIGHT);
          }

climate:
  - platform: tclac
    name: "${device_name} Climate"
    id: ${device_name}climate
    
