Name: Compile ESPHome

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: |
          pip3 install esphome

      - name: Build ESPHome Firmware
        run: |
          esphome compile TCL-Conditioner.yaml

      - name: Extract and Rename Firmware
        run: |
          mkdir -p output
          # البحث عن ملف الـ factory الكامل المخصص للإقلاع لأول مرة
          find . -name "firmware.factory.bin" -exec cp {} output/tclac_firmware_factory.bin \; 2>/dev/null || true
          
          # خطوة احتياطية في حال لم يجد الاسم السابق بالكامل
          find . -name "*factory*.bin" -exec cp {} output/tclac_firmware_factory.bin \; 2>/dev/null || true

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: tclac_firmware
          path: output/tclac_firmware_factory.bin
          
